RandyGaul/cute_framework

src/cute_draw.cpp

Flipped some signs to draw the outer arcs, not the inner arcs.

Fix drawing capsule shapes

---

include/cute_math.h

Add function for reflecting a vector off a plane

Add cf_reflect_v2 to cf_math.h

---

src/cute_draw.cpp

Fix scale before rotation

---

include/cute_array.h
include/cute_defines.h
include/cute_hashtable.h
include/cute_string.h

Rename move to cf_move

---

docs/topics/coroutines.md

Thanks for linking to my article. I've moved domains since then, so the link should be updated. :)

Update coroutines article link

---

libraries/cute/cute_tls.h

Cast data to uintptr_t before doing arithemtic

---

src/cute_draw.cpp

updates fetch_content for sprites created from png that have no animation

update fetch_content for sprites created from png

---

CMakeLists.txt

Bump SDL2 to 2.30.5

---

libraries/cute/cute_sync.h

I added a count of queued/running tasks that gets decremented whenever a thread finishes. The kick_and_wait function will now wait until this count is 0 before returning.

Add tasks_running count and wait for it to reach 0 before returning from cute_threadpool_kick_and_wait

---

src/cute_graphics.cpp

I don't know if this is the right way to do this. It solved my problem so I figured I'd open a PR to discuss. Would it be better to instead do something like a pow2 resize?

Resize vertex buffer if necessary in cf_mesh_update_vertex_data

---

CMakeLists.txt

Ignore the commits that make me seem like a crazy person...

Add target_dxc_copy and better defaults

---

src/cute_app.cpp

Related: https://github.com/libsdl-org/SDL/commit/b17ca32d8cafbd6a6524f49485208842adca66b8

Use SDL's updated driver names

---

include/cute_graphics.h
libraries/SDL_gpu_shadercross/SDL_gpu_shadercross.h
src/cute_graphics.cpp
src/cute_imgui.cpp
src/internal/cute_graphics_internal.h

This PR addresses changes done in [SDL3 rename PR](https://github.com/libsdl-org/SDL/pull/10730).
This mostly implements the necessary renames of the structs and fields of those structs.
> [!NOTE]
This PR includes changes from https://github.com/RandyGaul/cute_framework/pull/215. I'm happy to remove this and rebase once a working, green master branch is available.

Sync with sdl3 renames

---

src/cute_app.cpp
src/cute_graphics.cpp
src/cute_imgui.cpp

Addresses https://github.com/libsdl-org/SDL/commit/d3091b95389a657c041d50e5d80df28f2e1e4dbb
and https://github.com/libsdl-org/SDL/pull/10767

Sync with blit info and stencil info updates

---

libraries/SDL_gpu_shadercross/SDL_gpu_shadercross.h
src/cute_app.cpp
src/cute_graphics.cpp
src/cute_imgui.cpp

Relevant SDL commits:
https://github.com/libsdl-org/SDL/commit/a45a2caf4930274b012d4b3c0fa22cd66285f173
https://github.com/libsdl-org/SDL/commit/96e147b2b9528d26a5095fb405e259bbb6484173
_If you want me to reword the commit message let me know, I know it's ugly._

Replace SDL_GetGPUDriver with SDL_GetGPUShaderFormats and SDL_GPUVertexBinding with SDL_GPUVertexBufferDescription

---

CMakeLists.txt

Only tested on Linux so far but hot reload works.

Make it possible to build as a dynamic library

---

samples/scratch.cpp
src/cute_draw.cpp
src/cute_graphics.cpp

I left in scratch.cpp so that you could see what I tested. I'm pretty sure I covered them all but, feel free to give it a look-over.

Halve the stroke in s_draw_vs and fix related calls in cute_draw. (cf_draw_arrow, cf_draw_polyline, cf_draw_line)

---

samples/scissor.c
src/cute_draw.cpp

I believe the logic is flipped.

Fix logic for render command merging

---

include/cute_app.h
src/cute_app.cpp

This adds 2 framerate functions.
@RandyGaul Let me know if you are ok with the naming.

Framerate functions

---

include/cute_app.h
src/cute_app.cpp

There's an error power state that we were not handling.

Add missing power state

---

README.md

I think it would be neat to have more demoable stuff presented in the README to show what the framework is about. This could bring in more people. Let me know what you think @RandyGaul!

Add a demo game image to README

---

CMakeLists.txt

Bump SDL to 3.2.16

---

.github/workflows/documentation.yml

This PR updates the flow according to the https://github.com/actions/deploy-pages

Update the doc build flow

---

include/cute_draw.h
include/cute_math.h
src/cute_draw.cpp

Make V2 arrays consts

---

CMakeLists.txt

This PR sets some basic project settings, such as the description, URL and the version, so this can be reused in other parts when building.

CMake project settings

---

CMakeLists.txt
samples/scratch.cpp
src/cute_app.cpp

Confirmed on both Windows and Linux that the icon will show up with the correct color after this.

Fix cf_app_set_icon

---

.github/workflows/build.yml
.github/workflows/documentation.yml

Use up to 4 threads

---

src/cute_app.cpp
src/cute_graphics.cpp
src/internal/cute_graphics_internal.h

It is coarse-grained but probably useful enough to narrow down the erroneous part and check with a graphic debugger.

Sprinkle the OpenGL error check macro at different points in the code

---

docs/topics/dear_imgui.md

I went ahead and updated the documentation. I also simplified some of the paragraphs to cut on words and increase signal-to-noise a little bit.
Closes https://github.com/RandyGaul/cute_framework/issues/364.

ImGui docs update

---

docs/made_with_cf.md
mkdocs.yml

Docs: Add Made with CF page
