include/cute_input.h
This `enum my_type : int` is not valid syntax in C
=> Fix invalid c99 syntax

docs/topics/drawing.md
Just fixes a minor docs typo in a URL that was causing a 404.
=> Docs: Fix URL to low_level_graphics from Drawing page

include/cute_color.h
Users will assume hex is in RGBA format, not ABGR
=> Fix cf_make_color_hex returning backwards results

include/cute_draw.h, src/cute_draw.cpp
Support drawing partial strings with cf_draw_text while not requiring the user to create temporary strings.
=> Add text_length to cf_draw_text

src/cute_hashtable.cpp, test/test_hashtable.cpp
Write the found index from `cf_hashtable_find_impl2` to `hhdr->return_index` so the `hget_ptr` macro can use it
=> Fix the hget_ptr macro returning the wrong value

include/cute_hashtable.h, test/test_hashtable.cpp
Previously the macro `cf_hashtable_has` was set to use the `cf_hashtable_remove_impl`function
=> Fix cf_hashtable_has macro

src/cute_file_system.cpp, test/test_path.cpp
If a user passes in a path string to `cf_path_get_filename` that contains no "/" separators, assume that string is the filename. Return a copy of that string instead of `NULL`
=> cf_path_get_filename - support path string arguments with no "/" seperators

src/cute_file_system.cpp, test/test_path.cpp
I just did the bare minimum to support the use-case. Sorry about the extra commit... CLion didn't realize the file was tabs for some reason.
=> Allow dots in normalized paths

include/cute_sprite.h, src/cute_sprite.cpp, test/test_sprite.cpp
I'm loading sprites from a png while trying to integrate with cute_tiled, and wanted to be able to easily unload the sprites when I switch levels.
=> Add cf_easy_sprite_unload

src/cute_draw.cpp
`cf_camera_dimensions` appears to divide the passed in width and height by 2. This PR just makes it so that when we peek at the dimensions, we get the same thing we passed in.
```c++
cf_camera_dimensions(320, 180);
v2 dim = cf_camera_peek_dimensions();
ImGui::Text("%f, %f", dim.x, dim.y); // displays 160, 90
```
=> Return the same camera dimensions that were passed in

CMakeLists.txt, src/cute_aabb_tree.cpp, test/main.cpp, test/test_aabb.cpp
We should probably destroy the `CF_AabbTreeInternal` when calling destroy instead of making more. 😜
=> Use tree_handle to destroy CF_AabbTreeInternal correctly

include/cute_array.h
I also inverted the comaprison order of the if-statement to match the `ensure_count` function. It's still doing the same comparison.
=> Make Array<T>::set_count ensure the count and calls destructors properly

samples/scratch.cpp
Since the stacks of states always get reset every frame, the scratch example will crash if it only push the font once.
=> Ensure that font is always pushed in scratch example

include/cute_color.h
CF_Pixel conversion functions that used bitwise operations were assuming an `rgba` byte order, but the correct byte order is `abgr`
=> Fix CF_Pixel conversion functions

libraries/cute/cute_sound.h
When you use negative pitch and sample count < 0 then you'll get a crash on next read.
Also adjusted next play sample index when looping with negative pitch to avoid any audio clipping from happening.
=> Negative pitch loop and crash fix

src/cute_app.cpp
when using CF_TemporaryImage with cf_fetch_image(), spritebatch_defrag() will thrash the atlas texture before imgui gets to use it causing sokol to give you a bunch of errors
=> moving spritebatch_defrag() to cleanup phase

include/cute_defines.h
When the current architecture lacks SSE instructions, force the sound module's mode to scalar.
This allows for a successful build on eg. ARM64 Ubuntu 22.04.
Fixes #167
=> Use scalar mode on ARM Linux

include/cute_draw.h, src/cute_audio.cpp
- The wrapper functions in `cute_draw.h` are meant to return bool type, however the return values of internal `cf_*` functions which are called aren't stored or returned, thus making these functions return nothing. Easily fixed by calling the internal functions within the wrapper and returning the returned values.
- In `cute_audio.cpp`, a NULL was returned previously. Due to `CF_Audio` having just one field in the struct for the data, that would mean the NULL would be cast to uint64_t. This means that comparing the return value from `cf_audio_load_*` functions to NULL would not yield any actual results in some scenarios, as the value would be cast to `uint64_t`, resulting in undefined behavior. Solution is simple, just return an empty `CF_Audio` struct. Then, if needed, the return value …
=> fix: implied return and NULL cast to uint64_t

include/cute_input.h, src/cute_input.cpp
`cf_key_up()` is referenced in the docs but is nowhere to be found.
The implementation follows `cf_key_down` but I'm not sure if it should be closer to the implementation of the `cf_key_just_released`.
=> Add missing cf_key_up()

CMakeLists.txt
This commit updates the CMakeLists.txt file to use the correct directory when copying over the sample data when building from source directory.
Previously, the sample data was copied from the top-level CMake working dir, which wouldn't work when the samples were being built from a project including CF.
With this change, the sample data should be copied over from the CF working directory, which should work in all cases.
=> Use correct directory when copying sample data

CMakeLists.txt
The cloning process is very slow compared to downloading a tar/zip, which improves on the build times in CI and developer experience, too.
=> Download packages rather than clone

CMakeLists.txt
Tests and samples should only be build when building cute directly as a project. They should be skipped completely when using cute as a dependency.
=> Build tests and samples separate

src/cute_symbol.cpp
This fixes a compile error on gcc without `-fpermissive`.
=> Explicitly cast returned pointer in cute_symbol to void*

src/cute_graphics.cpp
Resolves this warning:
```
build/_deps/cute-src/src/cute_graphics.cpp:1064:8: warning: extra tokens at end of #endif directive [-Wextra-tokens]
#endif CF_RUNTIME_SHADER_COMPIILATION
```
=> Remove extra tokens

src/cute_graphics.cpp
I introduced this bug; sorry. We were doing a memcpy after the resize, reading from `data` using the new size.
=> Same resize behavior, but without reading out of bounds

.github/workflows/build.yml
GitHub Actions are run on machines with 4 cores. This change sets the parallel level to number of cores + 2. It cut down the time for the Linux build from 17 minutes to 7 minutes.
This can also be configured as an argument to `cmake` using `--parallel 6`.
=> Build in parallel

src/cute_graphics.cpp
Similarly to https://github.com/cocos2d/cocos2d-x/pull/19774/files, we default to `CF_PIXEL_FORMAT_D32_FLOAT_S8_UINT` and set it to `CF_PIXEL_FORMAT_D24_UNORM_S8_UINT` if it's supported.
=> Check support for texture format

src/cute_app.cpp
In order to use `cf_default_display` we need to first initalize the video subsystem.
I've also added https://github.com/RandyGaul/cute_framework/commit/9ae12223e8f73337b027f59c4e3b7a1b6acd8972, but I'm happy to remove it if that's not something we want to do.
=> Init video subsystem

.github/workflows/build.yml, CMakeLists.txt
This PR allows the user to specify `CF_FRAMEWORK_APPLE_FRAMEWORK=ON` to force generation of an `cute.framework` Apple framework.
Closes https://github.com/RandyGaul/cute_framework/issues/203
=> Allow configuring whether to build an Apple framework

CMakeLists.txt
Rather than doing the whole dance with custom downloading, use `FetchContent_Declare` and then perform a `PATCH_COMMAND` that executes the python script.
=> Simplify glslang dependency fetching

libraries/cute/cute_c2.h
Fixes:
```
libraries/cute/cute_c2.h:1333:10: warning: enumeration value 'C2_TYPE_NONE' not handled in switch [-Wswitch]
switch (type)
^~~~
libraries/cute/cute_c2.h:1333:10: note: add missing switch cases
```
=> Add missing switch cases

src/cute_graphics.cpp
I didn't add cf wrappers around the new SDL functions. It looks like that's in another PR. (I can add them if you'd like here though.)
This PR just applys the stencil in cf_apply_shader when the renderpass is created.
=> Apply stencil when creating render pass in cf_apply_shader

src/cute_sprite.cpp
Fixes warning: 'sprintf' is deprecated: This function is provided for compatibility reasons only.  Due to security concerns inherent in the design of sprintf(3), it is highly recommended that you use snprintf(3) instead. [-Wdeprecated-declarations]
=> Use snprintf

CMakeLists.txt, samples/scissor.c, src/cute_draw.cpp
`cf_apply_shader` creates a `SDL_GPURenderPass` so viewport and scissor state have to be applied after that.
=> Fix scissor and viewport application order

src/cute_string.cpp
I was running my program through AddressSanitizer and these show up:
* cf_serase: `scount` already includes the null terminator so +1 is redundant.
* cf_sreplace: `remaining` is wrongly calculated based on `with_len` instead of `replace_len`. We want to overwrite the replaced substring with what follows after it so `replace_len` should be used in all cases.
The current code works in most cases since a new page is zero filled and accessing out of bound will just return 0.
But it will break if the string lies near the border of a page or the allocator recycle some memory chunks.
=> Fix string manipulation functions

src/cute_draw.cpp, src/cute_sprite.cpp
* cf_easy_sprite_unload: This should free the image before removing the sprite entry. Otherwise, the image pointer would be invalidated.
* cf_get_pixels: Guard against invalid id when handling font and easy sprite. This is because after a resource is unloaded, its id still lingers in the batcher for a while.
=> Fix memory error when unloading easy sprite

libraries/SDL_gpu_shadercross/SDL_gpu_shadercross.h, src/cute_app.cpp
This PR updates the shadercross dependency to incorporate all the newest changes.
What I'm not sure about, is after https://github.com/flibitijibibo/SDL_gpu_shadercross/commit/c776f225aca7add078874516694b898ec96146ac#diff-85d451ecdc5be12bf18bd38506d3f9ea7746cd7b8ea990b9faccf05e854746e1R22, do we need to use the `SDL_ShaderCross_GetHLSLShaderFormats()`?
=> Bump shadercross

CMakeLists.txt, include/cute_input.h, samples/ime.c, src/cute_input.cpp
* Allow grabbing the entire text input buffer.
At least it is useful for my IME which sends an entire composed word.
* Replace rather than append composition.
It is what the IME is "cooking".
At least on Linux, the IME handles text replacement and the application just have to render.
* Add an IME example.
Only tested with https://en.wikipedia.org/wiki/UniKey_(software) on Linux but SDL **should** be portable.
There are a few things that may need further thoughts:
Should `cf_draw_text` accepts `NULL` as input and treat it as an empty string?
CF allows initializing a string as `NULL` and manipulate it.
So `NULL` is equivalent to an empty string.
Do we need a way to render text from utf32?
The current example keeps 2 concurrent representations: utf8 and utf32.
utf32 is for editing since each …
=> Improve IME and text input support.

src/cute_draw.cpp
cute_png_cache is using the framework's allocator while cute_png uses libc.
If the allocator is replaced, there will be a crash on exit.
=> Make cute_png use framework's allocator

include/cute_sprite.h
The sprite would loop properly in ping pong mode.
If loop is set to false, it will bounce back once and stop.
=> Fix looping behaviour for pingpong animation

src/cute_graphics.cpp
The hashmap removal would invalidate the earlier pointer and a different blit shader would be destroyed.
A blit shader is not mapped to anything so I think it safe to remove the mapping later.
=> Fix cf_destroy_shader

src/cute_app.cpp
This fixes the HighDPI mode rendering on macOS.
https://wiki.libsdl.org/SDL3/SDL_CreateWindowWithProperties
=> Set high density window property

samples/recolor.cpp
Original code was throwing this error:
```
error: embedding a #include directive within macro arguments is not supported
8 |         #include "blend.shd"\n
```
This change uses literal concatenation to merge the header include directive as a string with the rest of the shader code.
=> Fix undefined behaviour in the shader definition

.github/workflows/build.yml
This fixes the following error: `'gameinput.h': No such file or directory`
https://github.com/actions/runner-images/issues/10980
=> Use newer Windows build

CMakeLists.txt, src/cute_app.cpp
This PR upgrades SDL to version 3.2.6.
Rearranged the threadpool destroy before the `SDL_Quit` as I was getting:
```
2025-03-03 06:38:29.661 easysprite[92289:5369682] Leaked thread (0x600000181b20)
2025-03-03 06:38:29.661 easysprite[92289:5369682] Leaked thread (0x600000181c00)
2025-03-03 06:38:29.661 easysprite[92289:5369682] Leaked thread (0x600000181ce0)
2025-03-03 06:38:29.661 easysprite[92289:5369682] Leaked thread (0x600000181dc0)
2025-03-03 06:38:29.661 easysprite[92289:5369682] Leaked thread (0x600000181ea0)
2025-03-03 06:38:29.661 easysprite[92289:5369682] Leaked thread (0x600000181f80)
2025-03-03 06:38:29.661 easysprite[92289:5369682] Leaked thread (0x600000182060)
2025-03-03 06:38:29.661 easysprite[92289:5369682] Leaked thread (0x600000181ab0)
2025-03-03 06:38:29.661 …
```
=> Bump SDL to 3.2.6

samples/platformer.cpp, src/cute_app.cpp, test/test_string.cpp
Removes the `unused return value` warning and `braces around scalar initializer`
=> Fix some annoying compile warnings

src/cute_app.cpp, src/internal/cute_app_internal.h
As per the conversation on Discord:
It's not used for anything and threadpools can be created manually.
=> Remove default threadpool

src/cute_draw.cpp
This ensures that the atlas is defragged before every flush.
Both RAM and VRAM usage are reduced significantly.
No change to the cycling flag is needed.
However, I have no idea how this affects performance since there is another per-frame defrag.
=> Defrag the sprite batcher before every flush

.github/workflows/build.yml, CMakeLists.txt
Rather than having all the libraries spread across all the dependency directories, this setting enforces one unified place where all the static and dynamic libraries are generated to.
This simplifies the task of finding the dynamic ones, and/or linking against when not using CMake as the build tool in the actual app.
```
🍔 ls build/lib
libcute-shader.a                      libSDL3.a              libSPIRV-Tools-lint.a
libcute.a                             libSDL3.dylib          libSPIRV-Tools-opt.a
libGenericCodeGen.a                   libSDL_uclibc.a        libSPIRV-Tools-reduce.a
libglslang-default-resource-limits.a  libspirv-cross-c.a     libSPIRV-Tools-shared.dylib
libglslang.a                          libspirv-cross-core.a  libSPIRV-Tools.a
libMachineIndependent.a …
```
=> CMake: Output all libraries to the same directory

docs/stylesheets/cute.css, mkdocs.yml
This PR sets up the Cute color scheme taken from the logo.
Pink for the currently active page color and header, green for the hover effect:
https://github.com/user-attachments/assets/2e309afe-d0d9-4ee0-b562-6689e9f6bac3
=> Cute color scheme

.gitignore, CMakeLists.txt, include/cute_version.h.in, src/cute_version.cpp.in
This PR configures the version source files as templates so that the version number can be injected from the CMake's project version.
Requires https://github.com/RandyGaul/cute_framework/pull/313
=> Cmake project settings version configure

CMakeLists.txt
This is useful when working on Unix systems, to have a default installation directory configured when using as a dependency.
=> Configure default install directories

.github/workflows/build.yml, .github/workflows/documentation.yml
This PR moves the parallel setting to the command line and uses the default number of threads, and ensures the apt packages are always up to date in the docs workflow.
=> Cmake tweaks

include/cute_graphics.h, src/cute_graphics.cpp, src/cute_shader/cute_shader.cpp, src/cute_shader/cute_shader.h
Vibecoding to check pixel format capabilities. This is a lot more important once we add GLES3 since I would expect much less support compared to SDL_Gpu, especially for web builds.
=> Add OpenGL pixel format querying and validation

CMakeLists.txt, include/cute_graphics.h, src/cute_app.cpp, src/cute_draw.cpp, src/cute_graphics.cpp, src/cute_graphics_glad.cpp, src/cute_graphics_gles.cpp, src/cute_graphics_sdlgpu.cpp, src/cute_imgui.cpp, src/internal/cute_app_internal.h, src/internal/cute_graphics_internal.h, src/internal/cute_imgui_internal.h
This is mostly a copy&paste refactor without major bug fixes.
But I submit first because it's huge although it's generally just moving code around.
* New backend type: [`CF_BACKEND_TYPE_GLES3`](https://github.com/bullno1/cute_framework/blob/4ec71fc7ad6e442c6d8cd5d4fe433bdab992dcdb/include/cute_graphics.h#L137)
This is recorded in `app->gfx_backend_type`.
* Split SDL_GPU and GLES3 into their own compilation units
* `cute_graphics` and `cute_app` dispatch to the appropriate backend based on `app->gfx_backend_type` with a [shim](https://github.com/bullno1/cute_framework/blob/4ec71fc7ad6e442c6d8cd5d4fe433bdab992dcdb/src/cute_graphics.cpp#L581-L601)
* Enable the GLES backend by default on emscripten: https://github.com/bullno1/cute_framework/blob/4ec71fc7ad6e442c6d8cd5d4fe433bdab992dcdb/src/cut …
=> Refactor graphic backends

samples/CMakeLists.txt, src/cute_draw.cpp, src/cute_graphics_gles.cpp, src/cute_graphics_sdlgpu.cpp, src/internal/cute_graphics_internal.h
This fixes uniform upload.
Reflection info from the compiler is used instead of assuming the uniform block name.
Shaders with more than one block (e.g: draw shader) should work now.
=> Fix uniform upload in GLES
